In [1]:
import numpy as np


In [2]:
## creating the 5x5 array with random number between 1 and 20 
array_1 = np.random.randint(1, 21, size=(5, 5))

# changing the third column as 1
array_1[:, 2] = 1
array_1

array([[14,  8,  1, 18, 14],
       [ 7, 11,  1, 13, 18],
       [ 1, 10,  1,  1,  2],
       [ 6,  8,  1, 13,  4],
       [ 9,  9,  1, 15,  7]], dtype=int32)

In [4]:
array_2 = np.arange(1, 37).reshape(6, 6)
subarr_1 = array_2[2:5, 2:4]
subarr_1

array([[15, 16],
       [21, 22],
       [27, 28]])

In [23]:
array_3 = np.random.randint(1, 21, size=(5,5))

array_3 = np.concatenate((array_3[0, :], array_3[-1, :], array_3[1:-1, 0], array_3[1:-1, -1]))
print(array_3)

[17 18 12 14  7 13  1  3  4  8 15  4  7 20  2 18]


In [17]:
array_3 = np.random.randint(1, 21, size=(5,5))
print(array_3)
print(array_3[:, -1])

[[18 15  6 20 16]
 [11  6  8 19 13]
 [ 7  8  9  8 20]
 [12 10 12 14  3]
 [ 9  9 17  2  7]]
[16 13 20  3  7]


In [26]:
array_4 = np.random.randint(1, 13, size=(3, 4))
array_5 = np.random.randint(1, 13, size=(3, 4))


In [27]:
array_4+array_5

array([[18, 13,  3, 19],
       [16, 13, 11, 12],
       [20,  9, 13,  7]], dtype=int32)

In [28]:
array_4 - array_5

array([[ 4, -9, -1,  3],
       [-2, -9, -9,  4],
       [ 0, -5, -9,  1]], dtype=int32)

In [29]:
array_5 * array_4

array([[ 77,  22,   2,  88],
       [ 63,  22,  10,  32],
       [100,  14,  22,  12]], dtype=int32)

In [30]:
array_4 / array_5

array([[1.57142857, 0.18181818, 0.5       , 1.375     ],
       [0.77777778, 0.18181818, 0.1       , 2.        ],
       [1.        , 0.28571429, 0.18181818, 1.33333333]])

In [32]:
array_6 = np.arange(1, 17).reshape(4, 4)
array_6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
np.sum(array_6, axis=1)

array([10, 26, 42, 58])

In [34]:
np.sum(array_6, axis=0)

array([28, 32, 36, 40])

In [38]:
array = np.random.randint(1, 25, size=(5, 5))
print(np.median(array))
print(np.std(array))
print(np.var(array))
print(np.mean(array))

10.0
7.0033135014791394
49.046400000000006
10.56


In [43]:
arr = np.arange(1, 10).reshape(3, 3)
mean = np.mean(arr)
standard_deviation = np.std(arr)
normalized_array = (arr - mean)/standard_deviation
normalized_array

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])